// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ipfs-force-community/chain-co/co (interfaces: INodeProvider)

// Package co is a generated GoMock package.
package co

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockINodeProvider is a mock of INodeProvider interface.
type MockINodeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockINodeProviderMockRecorder
}

// MockINodeProviderMockRecorder is the mock recorder for MockINodeProvider.
type MockINodeProviderMockRecorder struct {
	mock *MockINodeProvider
}

// NewMockINodeProvider creates a new mock instance.
func NewMockINodeProvider(ctrl *gomock.Controller) *MockINodeProvider {
	mock := &MockINodeProvider{ctrl: ctrl}
	mock.recorder = &MockINodeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINodeProvider) EXPECT() *MockINodeProviderMockRecorder {
	return m.recorder
}

// AddHook mocks base method.
func (m *MockINodeProvider) AddHook(arg0 func(map[string]bool)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHook", arg0)
}

// AddHook indicates an expected call of AddHook.
func (mr *MockINodeProviderMockRecorder) AddHook(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHook", reflect.TypeOf((*MockINodeProvider)(nil).AddHook), arg0)
}

// GetHosts mocks base method.
func (m *MockINodeProvider) GetHosts() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHosts")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetHosts indicates an expected call of GetHosts.
func (mr *MockINodeProviderMockRecorder) GetHosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHosts", reflect.TypeOf((*MockINodeProvider)(nil).GetHosts))
}

// GetNode mocks base method.
func (m *MockINodeProvider) GetNode(arg0 string) *Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", arg0)
	ret0, _ := ret[0].(*Node)
	return ret0
}

// GetNode indicates an expected call of GetNode.
func (mr *MockINodeProviderMockRecorder) GetNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockINodeProvider)(nil).GetNode), arg0)
}
