// Code generated by ./gen/perm-proxy. DO NOT EDIT.

package api

import (
	"context"
	"errors"
)

var ErrNotSupported = errors.New("method not supported")

type LocalAPIStruct struct {
	Internal struct {
		ListPriority func(p0 context.Context) (map[string]int, error) `perm:"read"`

		ListWeight func(p0 context.Context) (map[string]int, error) `perm:"read"`

		SetWeight func(p0 context.Context, p1 string, p2 int) error `perm:"admin"`
	}
}

type LocalAPIStub struct {
}

func (s *LocalAPIStruct) ListPriority(p0 context.Context) (map[string]int, error) {
	if s.Internal.ListPriority == nil {
		return *new(map[string]int), ErrNotSupported
	}
	return s.Internal.ListPriority(p0)
}

func (s *LocalAPIStub) ListPriority(p0 context.Context) (map[string]int, error) {
	return *new(map[string]int), ErrNotSupported
}

func (s *LocalAPIStruct) ListWeight(p0 context.Context) (map[string]int, error) {
	if s.Internal.ListWeight == nil {
		return *new(map[string]int), ErrNotSupported
	}
	return s.Internal.ListWeight(p0)
}

func (s *LocalAPIStub) ListWeight(p0 context.Context) (map[string]int, error) {
	return *new(map[string]int), ErrNotSupported
}

func (s *LocalAPIStruct) SetWeight(p0 context.Context, p1 string, p2 int) error {
	if s.Internal.SetWeight == nil {
		return ErrNotSupported
	}
	return s.Internal.SetWeight(p0, p1, p2)
}

func (s *LocalAPIStub) SetWeight(p0 context.Context, p1 string, p2 int) error {
	return ErrNotSupported
}

var _ LocalAPI = new(LocalAPIStruct)
