name: Docker Image CI

on:
  push:
    branches: ['release/**', 'dev/**', master]
    tags: ['**']
  workflow_dispatch:

jobs:

  build_docker_image:
    uses: filecoin-project/venus/.github/workflows/common_docker_image.yml@master
    secrets:
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
